name: Simple Action
run-name: ${{ github.actor }} is running action ğŸ‡®ğŸ‡±
on: [push]
jobs:
  Some-MyText:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
      # uses: actions/checkout@v3
      # - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      # - name: List files in the repository
      #   run: |
      #   ls ${{ github.workspace }}
      # - run: echo "ğŸ This job's status is ${{ job.status }}."`
